version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      timezone: 'Asia/Tokyo'
      time: '10:00'
    ignore:
      - dependency-name: '@types/node'
      - dependency-name: '@types/vscode'
