name: Release VS Code Extension

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write
  id-token: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npm install -g vsce ovsx

      - run: npm run build

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: ecs.vsix
          path: ecs.vsix

      - name: Publish to VSCode Marketplace
        run: vsce publish --packagePath ecs.vsix --pat "${{ secrets.VSCE_PAT }}"

      - name: Publish to Open VSX
        run: ovsx publish ecs.vsix -p "${{ secrets.OVSX_PAT }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: ecs.vsix
